function L = line(t, h, opts)
    arguments
        t (3,1) double
        h (3,1) double
        opts.LineStyle (1,1) string = '-'
        opts.LineWidth (1,1) double = 1.5
        opts.Color (1,3) double = [0 0 0]
        opts.Marker (1,1) string = 'o'
    end

    L = plot3([t(1) h(1)],[t(2) h(2)],[t(3) h(3)], ...
        'LineWidth', opts.LineWidth, ...
        'Marker', opts.Marker, ...
        'MarkerSize', opts.LineWidth, ...
        LineStyle=opts.LineStyle, ...
        Color=opts.Color, ...
        MarkerFaceColor=opts.Color, ...
        MarkerEdgeColor='none');
end